import io
import os
import random
import string

from PIL import Image
from atproto import Client


# The pool of characters Babel can use.
# Accurate to modern digital adaptations of the Library of Babel:
# 26 lowercase letters, space, comma, and period.
# No weighting is applied, giving each character a 1/29 chance.
CHARACTERS = string.ascii_lowercase + " ,."


def generate_text(min_length=20, max_length=300):
    length = random.randint(min_length, max_length)

    return "".join(
        random.choice(CHARACTERS)
        for _ in range(length)
    )


def generate_image():
    # Completely random 32x32 RGB pixels.
    pixels = bytearray(
        random.getrandbits(8)
        for _ in range(32 * 32 * 3)
    )

    image = Image.frombytes(
        "RGB",
        (32, 32),
        bytes(pixels),
    )

    buffer = io.BytesIO()
    image.save(buffer, format="PNG")

    return buffer.getvalue()


def main():
    handle = os.environ["BLUESKY_HANDLE"]
    app_password = os.environ["BLUESKY_APP_PASSWORD"]

    client = Client()
    client.login(handle, app_password)

    text = generate_text()
    image = generate_image()

    print("=== POSTS OF BABLE ===")
    print()
    print(text)
    print()
    print("Generating completely random 32x32 image...")

    response = client.send_image(
        text=text,
        image=image,
        image_alt="A completely random 32x32 pixel image generated by Posts of Bable.",
    )

    print()
    print("Posted successfully.")
    print(f"URI: {response.uri}")


if __name__ == "__main__":
    main()
